services:
    dddominio_event_sourcing.serialization.symfony_serializer:
        class: DDDominio\EventSourcing\Serialization\SymfonySerializer
        arguments: ["@serializer"]
        public: false
        lazy: true

    dddominio_event_sourcing.serialization.jms_serializer:
        class: DDDominio\EventSourcing\Serialization\JmsSerializer
        arguments: ["@jms_serializer"]
        public: false
        lazy: true
