services:
    dddominio_event_sourcing.snapshotting.doctrine_dbal_snapshot_store:
        class: DDDominio\EventSourcing\Snapshotting\Vendor\DoctrineDbalSnapshotStore
        arguments:
            - ""
            - ""

    dddominio_event_sourcing.snapshotting.mysql_json_snapshot_store:
        class: DDDominio\EventSourcing\Snapshotting\Vendor\MySqlJsonSnapshotStore
        arguments:
            - ""
            - ""

    dddominio_event_sourcing.snapshotting.snapshotter:
        class: DDDominio\EventSourcing\Snapshotting\Snapshotter

    dddominio_event_sourcing.snapshotting.console.initialize:
        class: DDDominio\EventSourcingBundle\Command\InitializeSnapshotStoreCommand
        arguments:
            -  "@dddominio.snapshot_store"
        tags:
            - { name: console.command }
